### ISSUE TITLE
Probleme de recherche

### ISSUE THREAD

**Issue by jurnet** [Snipees/couchpotato.providers.french#1]
Bonjour et beau travail.
Une petite question si vous activez les 2 providers et que vous cherchez par exemple SPY sortie en 2015
Impossible de trouver.
Avez vous une solution ?

**Comment by Snipees** [comment]
Bonjour,

Si une recherche ne retourne rien (alors que pour d'autres oui), il y a forcément une explication.
Le plus simple dans ce cas, c'est d'aller directement sur les tracker faire la recherche pour constater quels sont les résultats.

Pour ce film, le bluray ne sort que le 28 octobre, il est donc encore introuvable sur T411.
Par contre il existe bien sur CPasBien mais uniquement en qualité dvdrip, donc si vous avez recherché une qualité HD, c'est normal que la recherche n'ait rien retourné.

**Comment by jurnet** [comment]
Oui en faite je me suis mal exprimé, je sais très bien que ce film n'est pas sur t411 donc normal, par contre il existe en Webrip sur cpasbien, j'ai donc mis toutes les qualités possible dans un profil et j'ai lancé une recherche sur ce profil. et rien peut etre est-ce du a la qualité WebRip ?

Autre probleme encore, je pars sur une recherche tel que:

Cité des anges (uniquement T411)
Avengers 2015 (T411 et Cpasbien)
Spy (uniquement Cpasbien)
La dame en noir 2
Cité des anges OK
Avengers n'affiche que t411
Spy ne le trouve pas (car peut etre en webrip ?)
la dame en noir le trouve sur t411 comme ceci The Woman in Black 2 alors qu'il y a plus de seeder avec La dame en noir 2 -> comment faire pour qu'il recherche exactement le titre donnée ?

Avez vous une solution ?

**Comment by Snipees** [comment]
Il faut passer Couchpotato en mode Debug pour voir les recherches qu'il effectue et ce qu'il trouve.
Je vais faire quelques tests de mon coté.

**Comment by jurnet** [comment]
voila l'erreur :
ERROR
[                 cpasbien] Failed parsing cPASbien: Traceback (most recent call last):
  File "/var/opt/couchpotato/custom_plugins/cpasbien/main.py", line 116, in _search
    new['size'] = self.parseSize(str(size))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 6: ordinal not in range(128)

**Comment by xila76** [comment]
@jurnet  +1

as-tu trouver un fix?

**Comment by jurnet** [comment]
Non aucun fix du coup je fonctionne à l'ancienne

**Comment by xila76** [comment]
@Snipees une idée pour fix ce ptit pb?

**Comment by Snipees** [comment]
Il doit s'agir d'un problème avec le parser qui ne relève plus correctement les données sur le site. Généralement cela est dû au fait que les sites évoluent, il faut donc réécrire le parser en conséquence.

Malheureusement, je suis une bille en ce qui concerne l'écriture d'un parser et tout comme @jurnet je n'utilise (pour le moment) plus Couchpotato car j'avais relevé les mêmes anomalies. Entre deux, j'ai changé de serveur et je n'ai pas encore réinstallé CP pour creuser le problème.

Si je trouve un patch, je ne manquerai pas de corriger le parser en conséquence.
Mais pour le moment, je n'ai pas de solution à proposer. sry :(

**Comment by noxzobax** [comment]
Hello

J'ai trouvé sur un site le soucis pour l'encodage. Il faut ajouter les 3 lignes au début:

import sys
reload(sys)
sys.setdefaultencoding('utf-8')

Ensuite il restait un soucis avec le parseSize qui remontait toujours 0. Après quelques test j'ai trouvé que le problème venait du faite que l'information est marquée en Go ou Mo au lieu de Gb et Mb.
Il suffit donc de remplacer le texte comme ceci:

size = result.findAll(attrs = {'class' : ["poid"]})[0].text.replace('Go', 'Gb').replace('Mo', 'Mb')

Voila, 4h pour trouver tout ça. Je suis pas du tout programmeur n'y ne connais python ou les encodages ou le parsing web donc j'ai eu pas mal de chance. Il en faut parfois ;)

A bientôt

ps: attention, le site t411 change bientôt d'extension.

**Comment by Snipees** [comment]
Merci pour ta contribution @noxzobax, c'est gentil de nous venir en aide ;)
Par contre, juste pour être sûr, puis-je savoir de quel parser tu parles ? T411 ou cPasBien ?

Il me semble bien que tu parles de cPasBien, j'ai donc appliqué tes corrections dans une nouvelle branche: [patch_nox](https://github.com/Snipees/couchpotato.providers.french/tree/patch_nox)

N'ayant pas de CP sous la main pour le moment, je vous laisse tester ;)

**Comment by Snipees** [comment]
#7

**Comment by noxzobax** [comment]
Salut

Oui c est celui de cp. Désolé de la confusion.

Cdt

**Comment by ghost** [comment]
Tu peux merger je viens de tester ça fonctionne avec le fix ;)

**Comment by cyno** [comment]
Je confirme, le fix résout le crash ! +1 pour le merge ;)

**Comment by grillead** [comment]
Bonjour a tous et merci a toi Snipees pour ces plugins qui fonctionne nickel, j ai fai une modif pour avoir la recherche des titre en FR et le résumé en FR aussi si ca interesse fait signe :)

**Comment by Snipees** [comment]
Merci pour vos retours et sorry pour le délai... c'est que je n'utilisais plus Couchpotato.
Mais je vais certainement y revenir, (car Plex Requests m'intéresse beaucoup)

Le merge est effectué.
