### ISSUE TITLE
Erreur HTTP 503

### ISSUE THREAD

**Issue by Ryuk3n** [Snipees/couchpotato.providers.french#11]
Bonjour,

Depuis que j'ai mis cpasbien au niveau des plugins, je rencontre l'erreur suivante :

04-27 13:55:30 ERROR [                 cpasbien] Login to cPASbien failed: HTTP Error 503: Service Unavailable 

Du coup pas de recherche possible sur CouchPotato, avez-vous idée d'où cela provient ?

Merci d'avance pour votre aide.

R.

**Comment by dmnfr** [comment]
This could be due to cloudfare protection.
Solution could be to add a wrapper to workaround the protection : https://github.com/Anorov/cloudflare-scrape

**Comment by Snipees** [comment]
#28
