### ISSUE TITLE
N'apparaissent pas dans Couchpotato sur Synology ds216Play

### ISSUE THREAD

**Issue by christiga** [Snipees/couchpotato.providers.french#13]
Bonjour,
Est ce que ces plugins sont toujours compatibles?
J'ai effectué l'installation mais les plugins n'apparaissent pas dans la liste des searchers de couchpotato.
Merci

**Comment by Snipees** [comment]
Ces plugins peuvent avoir certaines difficultés pour fonctionner correctement (dû à l'évolution des trackers associés) mais dans tous les cas, tu devrais les voir apparaître dans la liste de Couchpotato.

**Comment by Snipees** [comment]
Ton problème ne serait-il pas le même que celui de @blablanumerodeux : #12

**Comment by tocks53** [comment]
bonjour,

J'ai également le même soucis. Lorsque je relance CP, il ne me charge pas les plugins. Rien dans logs ne parlent de t411.

Avez vous une procédure d'installation du provider lorsque nous utilisons le paquet couch sur synology ?

Merci

**Comment by christiga** [comment]
Bonjour,
Désolée je n'avais pas vu les réponses.
Cela a fonctionné pour moi après quelques semaines ... les trackers s'affichent bien.
Par contre il n'y a que t411 qui a des résultats, je n'ai jamais réussi à récupérer des films de cpasbien à partir de couchpotato.

**Comment by tocks53** [comment]
salut, merci pour le retour.

Peux tu me dire ou tu as mis les fichiers sur le syno et les droits sur les repertoires et fichiers ?

Merci

**Comment by christiga** [comment]
J'ai fait comme indiqué dans la doc, à savoir :
- les deux dossiers t411 et cpasbien tels quels dans  /usr/local/couchpotatoserver/var/custom_plugins
- le fichier namer_check.py dans /usr/local/couchpotatoserver/share/CouchPotatoServer/couchpotato/core/helpers

Il me semble pas avoir modifié les droits, ils sont en 755.
