### ISSUE TITLE
Titre en FR ? 

### ISSUE THREAD

**Issue by Lethtel** [Snipees/couchpotato.providers.french#14]
Bonjour à tous,

Apres avoir abandonné CP je me suis dit que j'allais retenter l'aventure.

Petit problème : Il semblerait que CP ne trouve pas énormément de résultat sur cpasbien a cause de la recherche qui se réalise sur le titre choisi dans CP et qui est souvent en anglais, hors sur cpasbien ils aiment bien les titres francais.

Par exemple : 
Je vais sur allocine et "la chute de londre" je l'ajoute à CP via le plugin,
CP le detecte comme "london has fallen" (il reconnait donc bien le film).
CP fait une recherche sur "london has fallen" et ne me retourne que les résultats de RARBG ou KickAss.

CP me propose pourtant : 
"London has fallen"
"Olympus has fallen 2"
"altacco al potere 2" (ITA)
"XXXXX" (le titre en japonais je ne peux pas le C/C)

Il y a-t-il un moyen de choisir le titre en francais ?

Merci.

**Comment by Lethtel** [comment]
apparemment le branch develop de CP a prévu cette option, mais du coup j'obtiens cette erreur quand on fait une recherche sur cpasbien : 

08-14 19:21:52 ERROR [   couchpotato.core.event] Error in event "movie.searcher.single", that wasn't caught: Traceback (most recent call last):
  File "D:\CouchPotatoServer\couchpotato\core\event.py", line 15, in runHandler
    return handler(_args, *_kwargs)
  File "D:\CouchPotatoServer\couchpotato\core\media\movie\searcher.py", line 200, in single
    log.info('Search for %s in %s%s', (default_title, quality['label'], ' ignoring ETA' if always_search or ignore_eta else ''))
TypeError: 'NoneType' object has no attribute '**getitem**'
encoding=cp1252 debug=False args=[] app_dir=D:\CouchPotatoServer data_dir=C:\Users\letht\AppData\Roaming\CouchPotato desktop=None options=Namespace(config_file='C:\Users\letht\AppData\Roaming\CouchPotato\settings.conf', console_log=False, daemon=False, data_dir=None, debug=False, pid_file='C:\Users\letht\AppData\Roaming\CouchPotato\couchpotato.pid', quiet=False)  

Aucun soucis en faisant une recherche sur RARBG

**Comment by WilfriedU** [comment]
Avez vous trouver une solution pour ce probléme ?
il peine à trouver des film sur torrent9 avec des titre anglais

**Comment by XavierTolza** [comment]
+1

**Comment by Lethtel** [comment]
J'ai abandonné couchpotato et je suis passé sur radarr.
Il s'agit d'un fork de sonarr qui se développe pas mal, et ça cherche sur des tracker prives grâce à jackett. (Ou public américain mais si le film est posté dessus en fr ça l'attrape quand même)

**Comment by WilfriedU** [comment]
Salut lethtel,

j'ai installé et configurer radarr seulement sur torrent9 il trouve bien les film via Jackett mais il ne telecharge rien. ile me dit "Unknown movie. Movie found does not match wanted movie."

**Comment by Miloune** [comment]
@WilfriedU,
Ce problème est remonté auprès de Raddar (Problème de date qui est en fin de titre au lieu d'être juste après le titre du film) (https://github.com/Radarr/Radarr/issues/1407).
Le project owner a dit qu'il ferait quelque chose pour ça, mais que ça ne viendrait pas tout de suite.

**Comment by WilfriedU** [comment]
merci @miloune pour la réponse avez vous d'autre provider francais qui fonctionne ? car t411.al n'est pas encore reconnu sur Jackett

**Comment by Miloune** [comment]
@WilfriedU , Si t411.al fonctionne si tu coches "Update to pre-release:" et que tu updates Jackket

**Comment by Snipees** [comment]
#28
