### ISSUE TITLE
Same error on every torrent

### ISSUE THREAD

**Issue by cyno** [Snipees/couchpotato.providers.french#15]
Hi,

I get the same error for every torrent I try to download.

`[ couchpotato.core.event] Error in event "quality.single", that wasn't caught: Traceback (most recent call last): File "/opt/CouchPotatoServer/couchpotato/core/event.py", line 15, in runHandler return handler(*args, **kwargs) File "/opt/CouchPotatoServer/couchpotato/core/plugins/quality/main.py", line 117, in single quality = db.get('quality', identifier, with_doc = True)['doc'] File "/opt/CouchPotatoServer/libs/CodernityDB/database_super_thread_safe.py", line 43, in _inner res = f(*args, **kwargs) File "/opt/CouchPotatoServer/libs/CodernityDB/database.py", line 944, in get raise RecordNotFound("Not found") RecordNotFound: Not found encoding=UTF-8 debug=False args=['--daemon'] app_dir=/opt/CouchPotatoServer data_dir=/home/pi/.couchpotato desktop=None options=Namespace(config_file='/home/pi/.couchpotato/settings.conf', console_log=False, daemon=True, data_dir=None, debug=False, pid_file='/home/pi/.couchpotato/couchpotato.pid', quiet=False)`

My Couchpotato setting:
- Version 13a19423 (29/05/2016 à 11:30:23)
- Updater git, master
- ID398

Note: CPasBien is the only Searcher enabled.

Thank you !

**Comment by devop06** [comment]
i have the same error... have you found any solution ?

**Comment by amertner** [comment]
I have looked into this and found the problem; the fix is quite simple.

In couchpotato/core/media/movie/searcher.py, in the single function, it goes through each of the qualities selected, including the very last (blank) one, which causes the error.

To fix it, add this to line 172 or so, right after quality_custom is defined:

`if q_identifier == '':
                   continue
`

**Comment by Nibeck1309** [comment]
Hello some people have tested this fix?

**Comment by Snipees** [comment]
#28
