### ISSUE TITLE
Cpasbien ne trouve rien

### ISSUE THREAD

**Issue by devop06** [Snipees/couchpotato.providers.french#17]
Bonjour
Concernant le provider cpasbien, il ne trouve absolument rien que ce soit titre en français ou anglais. J'ai les logs debug dev activés, aucunes erreurs quelqu'un peut m'aider ? 
Merci

**Comment by Jamyz** [comment]
Ceci est du a cloudflare..............
Sickrage a contourner le probleme....
En attendant une mise a jour on peut rien faire

**Comment by Snipees** [comment]
#28
