### ISSUE TITLE
cpabien n'apparait pas dans les providers

### ISSUE THREAD

**Issue by TheDuuude** [Snipees/couchpotato.providers.french#19]
Bonjour, 

J'ai effectué l'installation comme indiqué dans le read me, mais seul t411 est visible/activable dans les providers.

Est-ce qu'il y a une manip a effectuer en plus pour le faire apparaitre ? 

Merci pour les plugins en tout cas

**Comment by SebastienTolron** [comment]
Hello ,

Même problème de mon côté

Merci pour le travail effectué c'est très pratique !

**Comment by PastaGringo** [comment]
Hello!
Cpasbien apparaît correctement chez moi, entre TorrentBytes et Awesome-HD (Ubuntu 16.04).

**Comment by Snipees** [comment]
#28
