### ISSUE TITLE
Erreur recherche de film sur T411

### ISSUE THREAD

**Issue by Djedje93270** [Snipees/couchpotato.providers.french#22]
Salut je suis nouveau sur CP, j'ai bien installé tes providers Cpasbien et T411 ils apparaissent dans CP mais quand je cherche un film:

11-20 05:18:17
ERROR
[   couchpotato.core.event] Error in event "provider.search.torrent.movie", that wasn't caught: Traceback (most recent call last):
  File "C:\Users\djedj\AppData\Roaming\CouchPotato\application\CouchPotato-3.0.1.win32\couchpotato\core\event.py", line 15, in runHandler
  File "C:\Users\djedj\AppData\Roaming\CouchPotato\application\CouchPotato-3.0.1.win32\couchpotato\core\media\_base\providers\base.py", line 220, in search
  File "C:\Users\djedj\AppData\Roaming\CouchPotato\custom_plugins\t411\main.py", line 44, in _searchOnTitle
KeyError: 'torrents'
encoding=cp1252 debug=False args=['--quiet'] app_dir=C:\Users\djedj\AppData\Roaming\CouchPotato\application\CouchPotato-3.0.1.win32 data_dir=C:\Users\djedj\AppData\Roaming\CouchPotato desktop=<__main__.CouchPotatoApp; proxy of <Swig Object of type 'wxPyApp *' at 0x39f3460> > options=Namespace(config_file='C:\\Users\\djedj\\AppData\\Roaming\\CouchPotato\\settings.conf', console_log=False, daemon=False, data_dir=None, debug=False, pid_file='C:\\Users\\djedj\\AppData\\Roaming\\CouchPotato\\couchpotato.pid', quiet=True)
Merci de ton aide!

**Comment by Djedje93270** [comment]
Même chose sur la version RuudeBurger;

11-20 22:25:00 ERROR
[ couchpotato.core.event] Error in event "provider.search.torrent.movie", that wasn't caught: Traceback (most recent call last): File "C:\CouchPotatoServer\couchpotato\core\event.py", line 15, in runHandler return handler(_args, *_kwargs) File "C:\CouchPotatoServer\couchpotato\core\media_base\providers\base.py", line 235, in search self._searchOnTitle(title, media, quality, results) File "C:\Users\djedj\AppData\Roaming\CouchPotato\custom_plugins\t411\main.py", line 44, in _searchOnTitle for entry in output['torrents']: KeyError: 'torrents' encoding=cp1252 debug=False args=[] app_dir=C:\CouchPotatoServer data_dir=C:\Users\djedj\AppData\Roaming\CouchPotato desktop=None options=Namespace(config_file='C:\Users\djedj\AppData\Roaming\CouchPotato\settings.conf', console_log=False, daemon=False, data_dir=None, debug=False, pid_file='C:\Users\djedj\AppData\Roaming\CouchPotato\couchpotato.pid', quiet=False)

**Comment by Nibeck1309** [comment]
j'ai la même erreur pour Cpasbien

**Comment by Snipees** [comment]
#28
