### ISSUE TITLE
Rajout des providers Xthor et Abnormal

### ISSUE THREAD

**Issue by hbooo** [Snipees/couchpotato.providers.french#24]
Bonjour, 

J'utilise CP avec Jackett afin d'avoir les providers Abnormal et Xthor, malheureusement Jackett est très instable et c'est la croix et la bannière pour qu'il ne crashe pas toutes les 5 minutes.

Serait il possible d'intégrer ces trackers dans ta liste de providers?

Voici le lien du provider pour jackett si cela peut aider à l'intégration?

https://github.com/Jackett/Jackett/blob/master/src/Jackett/Indexers/Abnormal.cs

Merci d'avance!

**Comment by Nicode70** [comment]
Ce serait effectivement super de pouvoir intégrer ces deux trackers

**Comment by Snipees** [comment]
#28
